"""
Unified request/response structures for all LLM API providers.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


class Provider(str, Enum):
    OPENAI = "openai"
    CLAUDE = "claude"
    GEMINI = "gemini"


# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------

@dataclass
class APIRequest:
    """Unified input structure for all LLM providers.

    Args:
        system_query:  The system prompt / instruction.
        user_query:    The user message.
        model:         Model identifier (provider-specific string, e.g.
                       "gpt-4o", "claude-sonnet-4-6", "gemini-2.0-flash").
        max_tokens:    Upper bound on response tokens (default 1024).
        temperature:   Sampling temperature 0–2 (default 0.7).
        metadata:      Arbitrary caller-supplied key/value pairs that are
                       round-tripped into the corresponding APIResponse.
        request_id:    Auto-generated UUID; override if you need a stable id.
    """

    system_query: str
    user_query: str
    model: str
    max_tokens: int = 1024
    temperature: float = 0.7
    metadata: dict[str, Any] = field(default_factory=dict)
    request_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def to_dict(self) -> dict[str, Any]:
        return {
            "request_id": self.request_id,
            "system_query": self.system_query,
            "user_query": self.user_query,
            "model": self.model,
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
            "metadata": self.metadata,
        }


# ---------------------------------------------------------------------------
# Response
# ---------------------------------------------------------------------------

@dataclass
class APIResponse:
    """Unified output structure returned by every API call.

    Fields:
        content:        The text generated by the model (empty on error).
        model:          Model string echoed from the raw API response.
        provider:       Which provider produced this response.
        request_id:     Echoed from the originating APIRequest.
        success:        False when an API or network error occurred.
        error:          Human-readable error message when success=False.
        usage:          Token-count breakdown (varies by provider):
                            {"prompt_tokens": int, "completion_tokens": int,
                             "total_tokens": int}
        metadata:       Merged dict of the request metadata plus any
                        response-level keys added by the provider adapter.
        latency_ms:     Wall-clock milliseconds for the API round-trip.
        raw_response:   The raw dict returned by the provider SDK/HTTP layer.
                        Useful for debugging; set to {} on error.
    """

    content: str
    model: str
    provider: Provider
    request_id: str
    success: bool
    error: Optional[str] = None
    usage: dict[str, int] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    latency_ms: float = 0.0
    raw_response: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "request_id": self.request_id,
            "provider": self.provider.value,
            "model": self.model,
            "success": self.success,
            "content": self.content,
            "error": self.error,
            "usage": self.usage,
            "metadata": self.metadata,
            "latency_ms": self.latency_ms,
        }

    @classmethod
    def error_response(
        cls,
        request: APIRequest,
        provider: Provider,
        error: str,
        latency_ms: float = 0.0,
    ) -> "APIResponse":
        """Convenience constructor for failed responses."""
        return cls(
            content="",
            model=request.model,
            provider=provider,
            request_id=request.request_id,
            success=False,
            error=error,
            usage={},
            metadata=dict(request.metadata),
            latency_ms=latency_ms,
            raw_response={},
        )


# ---------------------------------------------------------------------------
# Simple timer helper used by provider adapters
# ---------------------------------------------------------------------------

class _Timer:
    def __enter__(self) -> "_Timer":
        self._start = time.perf_counter()
        self.elapsed_ms = 0.0  # available immediately inside the with-block
        return self

    def __exit__(self, *_: Any) -> None:
        self.elapsed_ms = (time.perf_counter() - self._start) * 1000.0
